dr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls'))
]

portal/urls.py
from django.urls import path

from . import views

app_name = 'portal'
urlpatterns = [
	path('', views.index, name='index'),
	path('portal/person/<int:person_id>', views.show_person, name='show_person'),
    path('portal/person/add', views.add_person, name='add_person'),
	path('portal/person/adddata', views.add_person_data, name='add_person_data'),
	path('portal/person/safe', views.show_safe_persons, name='show_safe_persons'),
	path('portal/person/search_results', views.search_results, name='search_results'),
    # to do: add more paths...
]

portal/models.py
from django.db import models

class Event(models.Model):
    CATEGORY = (
        ('fire', 'Fire'),
        ('earth', 'Earth'),
        ('water', 'Water'),
        ('storm', 'Storm'),
        ('disease', 'Disease'),
        ('industrial', 'Industrial')
    )

    SEVERITY = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    )

    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(null=True, default=None, blank=True)
    location = models.CharField(max_length=200)
    severity = models.CharField(max_length=10, choices=SEVERITY,
                                default='medium')
    category = models.CharField(max_length=10, choices=CATEGORY,
                                default='fire')

    def __str__(self):
        return "{} [{}] at {}".format(
            self.name, self.severity, self.location)


class PersonStatus(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    other_name = models.CharField(max_length=50)
    status = models.ForeignKey(PersonStatus, on_delete=models.CASCADE, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    id_number = models.IntegerField()
    mobile = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return (self.first_name + ' ' + self.last_name)

portal/views.py
from django.shortcuts import get_object_or_404, redirect, render
# from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404

from django.db.models import Q
from .models import Event, Person, PersonStatus

def index(request):
	return render(request, 'portal/index.html')


def add_person_data(request):
    # if request.method == 'POST':
        # ...
        # return redirect('portal:index')
            #     <p>First Name <input type="text" name="first_name" id="first_name"></p>
            # <p>Last Name <input type="text" name="last_name" id="last_name"></p>
            # <p>Other Name <input type="text" name="other_name" id="other_name"></p>
            # status
            # <p>ID Number <input type="text" name="id_number" id="id_number"></p>
            # <p>Mobile <input type="text" name="mobile" id="mobile"></p>
            # <p>Email <input type="text" name="email" id="email"></p>
            # <p>Description <input type="text" name="description" id="description"></p>
            # <input type="submit" value="Add">
    
    try:
        print('here')
        print(request.POST['first_name'])
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        other_name = request.POST['other_name']
        id_number = request.POST['id_number']
        mobile = request.POST['mobile']
        email = request.POST['email']
        description = request.POST['description']
        events = Event.objects.all()
        # print(events[0].id)
        # print(events[0].name)
        # print(events)
        e = Event.objects.get(name='fire_sale')
        statusall = PersonStatus.objects.all()
        print(statusall[0].id)
        print(statusall[0].name)
        print(statusall)
        s = PersonStatus.objects.get(pk=request.POST['status'])
        p = Person(first_name=first_name, last_name=last_name, other_name=other_name, 
        id_number=id_number, mobile=mobile, email=email, description=description,
        event=e, status=s)
        print(p)
        p.save()
        return render(request, 'portal/add_person.html', 
            {'message': "You have saved the rental!", 'type_message':'success'})
    except:
        return render(request, 'portal/add_person.html', 
            {'message': "Please type a value!", 'type_message':'error'})
    

def add_person(request):
    # if request.method == 'POST':
        # ...
        # return redirect('portal:index')
    return render(request, 'portal/add_person.html')

def show_person(request, person_id):
    # 
    # try:
    #     # print(rental_id)
    #     person = Person.objects.get(pk=person_id)
    #     return render(request, 'person_details.html', {'person': person})
    # # print(rental_id)
    # except:
    #     rentals_withreturn = Rental.objects.all().exclude(return_date=None).order_by('-rental_date')
    #     rentals_noreturn = Rental.objects.all().filter(return_date=None).order_by('-rental_date')
    #     # print(rentals_withreturn)
    #     # print(rentals_noreturn)
    #     return render(request,'rentals.html', {'rentals_withreturn': rentals_withreturn, 
    #         'rentals_noreturn': rentals_noreturn})
    # try:
    print(person_id)
    person = Person.objects.get(pk=person_id)
    print(person)
    print(person_id)
    return render(request, 'portal/person_details.html', {'person': person})
    # except:
        # return render(request, 'portal/person_show_error.html')
    


def show_safe_persons(request):
    person_status = PersonStatus.objects.get(name='safe')
    persons = Person.objects.all().filter(status=person_status) 
    return render(request, 'portal/show_persons.html', {
        'title': 'Persons marked as Safe',
        'main_heading': 'Persons Marked as Safe',
        'persons': persons })


def search_results(request):
    context = None
    if request.method != 'POST':
        return redirect('portal:index')

    text = request.POST.get('search', '').strip()
    results = Person.objects.filter(
         Q(first_name__icontains=text) |
         Q(last_name__icontains=text) |
         Q(other_name__icontains=text) |
         Q(description__icontains=text))
    return render(request, 'portal/show_results_search.html', {
            'title': 'Search Results',
            'main_heading': 'Search Results',
            'results': results
        })

portal/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style type="text/css">
      .status-missing {
        font-weight: bold;
        color: red;
      }
      .status-safe {
        font-weight: bold;
        color: green;
      }
    </style>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block nav %}
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="" />
        Disaster Rescue
      </a>
      <div>
        <form class="form-inline" method="post" action="{% url 'portal:search_results' %}">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Search People" aria-label="Search People" name="search" required>
          <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
        </form>
      </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
  </body>
</html>

portal/templates/portal/add_person.html
{% extends 'base.html' %}
{% block title %}Person Search{% endblock %}
{% block content %}  
<!DOCTYPE html>
<html>
<head>
	<title>	Add a Person </title>
</head>
<body>
		<div class="container py-2">
		<h1> Add a Person </h1>
		</div>
		{% if type_message %}
			{% if type_message == 'error' %}
				<div class="container alert alert-danger">
			{% else %}
				<div class="container alert alert-success">
			{% endif %}
					{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
				</div>
		{% endif %}		
		<div class="container">
			<form action="{% url 'portal:add_person_data' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
				<p>First Name <input type="text" class="form-control" name="first_name" id="first_name"></p>
				
				<div class="form-group">
				<p>Last Name <input type="text" class="form-control" name="last_name" id="last_name"></p>
				</div>

				<div class="form-group">
				<p>Other Name <input type="text" class="form-control" name="other_name" id="other_name"></p>
				</div>

				<div class="form-group">
				<p>Status ID <input type="text" class="form-control" name="status" id="status"></p>
				</div>

				<div class="form-group">
				<p>ID Number <input type="text" class="form-control" name="id_number" id="id_number"></p>
				</div>

				<div class="form-group">
				<p>Mobile <input type="text" class="form-control" name="mobile" id="mobile"></p>
				</div>

				<div class="form-group">
				<p>Email <input type="text" class="form-control" name="email" id="email"></p>
				</div>

				<div class="form-group">
				<p>Description <input type="textarea" class="form-control" name="description" id="description"></p>
	   			</div>

	   			<input type="submit" class="btn btn-primary" value="Add">
   			</form>
   		</div>


</body>
</html>

{% endblock %}

portal/templates/portal/index.html
{% extends 'base.html' %}
{% block title %}Person Search{% endblock %}
{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Disaster Rescue</h1>
      <p>Disasters happen. And when they do, we're here to help. You can easily enter details of people who are, or who might be, affected by a diaster event. You can also search for people and update their statuses.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Add a Person</h2>
        <p>Add a person's details to our database. Please include as many details as you can, to assist rescue staff in identifying the person. </p>
        <p><a class="btn btn-secondary" href="{% url 'portal:add_person' %}" role="button">Add Person &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Safe People</h2>
        <p>View the list of people who are recorded as being safe. Please note that all data is to be taken as preliminary until it has been verified with evidence.</p>
        <p><a class="btn btn-secondary" href="{% url 'portal:show_safe_persons' %}" role="button">View Safe Persons &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Search for a Person</h2>
        <p>To search for a person, type your search text (eg. the person's name, ID number, etc.) in the search bar at the top of the page and click 'Search'.</p>
        
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

{% endblock %}

portal/templates/portal/person_detail.html
{% extends 'base.html' %}
{% block title %}Person Search{% endblock %}
{% block content %}  
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1> ID not found! </h1>  
      </div>
    </div>

{% endblock %}

portal/templates/portal/person_details.html
{% extends 'base.html' %}
{% block title %}Person Details{% endblock %}
{% block content %}  
  <div class="container alert alert-info my-3">
  	<!-- <div class="panel panel-default panel-body"> -->
    <!-- <div class="panel-body"> -->
        <h1> Name: {{ person.first_name }} {{ person.last_name }} </h1>
        <h2> Status: {{ person.status.name }} </h2>  
      <!-- </div> -->
  </div>

{% endblock %}

portal/templates/portal/person_show_error.html
{% extends 'base.html' %}
{% block title %}Person Search{% endblock %}
{% block content %}  
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1> ID not found! </h1>  
      </div>
    </div>

{% endblock %}

portal/templates/portal/show_persons.html
{% extends 'base.html' %}
{% block title %}Person Search{% endblock %}
{% block content %}  
  <head>
	<title>{{title}}</title>
</head>
<body>
	<div class="container my-3">
	<h1>{{main_heading}}</h1>
		<div class="list-group"> {% for person in persons %}
			<li class="list-group-item"> <a href = {% url 'portal:show_person' person.id %}> {{person}} </a></li>
			{% endfor %}
		</div>
	</div>
</body>
</html>
{% endblock %}

portal/templates/portal/show_results_search.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}  
  <head>
	<title>{{title}}</title>
</head>
<body>
	<div class="container my-3">
	<h1>{{main_heading}}</h1>
		<div class="list-group"> {% for person in results %}
		<li class="list-group-item"> <a href = {% url 'portal:show_person' person.id %}> {{person}} </li>
		{% endfor %}
		</div>
	</div>
</body>
</html>
{% endblock %}